### ISSUE TITLE
i saw the presentation, will it take a lot of CPU like spinlock while write is waiting?

### ISSUE THREAD

**Issue by hiqsociety** [jonhoo/left-right#103]
1. i saw the presentation, will it take a lot of CPU like spinlock while write is waiting?

2. eventual consistency? what kind of example is good to use as? coz if incremental count then will not work right?

**Comment by jonhoo** [comment]
Hi!

For 1, how many cycles will be spent waiting for readers will depend on how long reads take. The writer will end up waiting for the last reader to give up a read handle that it obtained prior to when the writer started waiting, which could be no time at all if all the readers have already moved on (or none were active), or it could take forever if a reader never drops their read handle. The waiting code is here:

https://github.com/jonhoo/left-right/blob/d6d13125af0b02f44bc299329d56773c2b913c7e/src/write.rs#L234

For 2, the eventual consistency part occurs because a writer's modifications are not visible until the writer publishes their changes. A writer could do many inserts into a left-right map for example, and none of them would appear to readers until `publish` is called. `publish` is defined here:

https://github.com/jonhoo/left-right/blob/d6d13125af0b02f44bc299329d56773c2b913c7e/src/write.rs#L302
