### ISSUE TITLE
Why you dont use Crossbeam Epoch?? i have question about this please help

### ISSUE THREAD

**Issue by Rustixir** [jonhoo/left-right#104]
hello ,

after I saw your video in youtube, attractive me to lock-free data structure.
after many times tried to read and coding about this topic.

crossbeam Epoch is mainly choice but have overhead of GC
and not is good document for newly version.

i want to know if is it good enough, why are you not using that for left-right
(also is core of evmap) ??

my second question is about crossbeam issue in newly version,
I become very happy if answer to my question, 

I opened issue but not anybody give answer
[Issue](https://github.com/crossbeam-rs/crossbeam/issues/820)

**Comment by jonhoo** [comment]
This is a synchronization primitive that serves much the same purpose as crossbeam epochs, except it's more efficient for a certain kind of use-case. There's no need to use crossbeam epochs in left-right since it already implements the relevant safety logic itself in a different way. So the answer is much the same as the reason for why `Arc` and `crossbeam::epoch` both exist — there is no "one best fits-all synchronization mechanism".

I can't speak to the crossbeam issue — I'm not a maintainer of crossbeam :)
